name:                pipes
version:             0.1.0.0
github:              "ambuc/pipes"
license:             BSD3
author:              "James Buckland"
maintainer:          "james.adam.buckland@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ambuc/pipes#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.41.2
- random >= 1.1
- vty >= 5.24

library:
  source-dirs: src

executables:
  pipes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes

tests:
  pipes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes
    - hspec >= 2.5.5
    - QuickCheck >= 2.11.3
    - Unique
